# Generated by Django 4.2.7 on 2026-01-06 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='test_cases',
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(help_text='Input for the test case')),
                ('expected_output', models.TextField(help_text='Expected output for the test case')),
                ('is_hidden', models.BooleanField(default=True, help_text='Whether this is a hidden test case')),
                ('order', models.IntegerField(default=0, help_text='Order of execution')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='problems.problem')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
