# Generated by Django 4.2.7 on 2026-01-04 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('problems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('language', models.CharField(choices=[('javascript', 'JavaScript'), ('python', 'Python'), ('java', 'Java'), ('cpp', 'C++')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('time_limit_exceeded', 'Time Limit Exceeded'), ('runtime_error', 'Runtime Error'), ('compilation_error', 'Compilation Error')], default='pending', max_length=30)),
                ('runtime', models.IntegerField(blank=True, help_text='Runtime in milliseconds', null=True)),
                ('memory', models.FloatField(blank=True, help_text='Memory usage in MB', null=True)),
                ('output', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('failed_test_case', models.JSONField(blank=True, null=True)),
                ('judge0_token', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
