# Generated by Django 4.2.7 on 2026-01-06 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='failed_test_case',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='judge0_token',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='memory',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='output',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='runtime',
        ),
        migrations.CreateModel(
            name='SubmissionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runtime', models.IntegerField(blank=True, help_text='Runtime in milliseconds', null=True)),
                ('memory', models.FloatField(blank=True, help_text='Memory usage in MB', null=True)),
                ('output', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('failed_test_case', models.JSONField(blank=True, null=True)),
                ('judge0_token', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='submissions.submission')),
            ],
        ),
    ]
