# Generated by Django 4.2.7 on 2026-01-06 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='easy_solved',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hard_solved',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_solved_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='medium_solved',
        ),
        migrations.RemoveField(
            model_name='user',
            name='streak',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_solved',
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_solved', models.IntegerField(default=0)),
                ('easy_solved', models.IntegerField(default=0)),
                ('medium_solved', models.IntegerField(default=0)),
                ('hard_solved', models.IntegerField(default=0)),
                ('streak', models.IntegerField(default=0)),
                ('last_solved_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
